spring.application.name=saborhub

# Database configuration
spring.datasource.url=jdbc:postgresql://db:5432/saborhub
spring.datasource.username=saborhub
spring.datasource.password=saborhub
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.placeholders.admin_login=${SABORHUB_ADMIN_LOGIN:admin}
spring.flyway.placeholders.admin_password=${SABORHUB_ADMIN_PASSWORD:admin}
spring.flyway.placeholders.admin_email=${SABORHUB_ADMIN_EMAIL:admin@saborhub.com}
spring.flyway.placeholders.admin_nome=${SABORHUB_ADMIN_NOME:Administrador}

api.security.token.secret=${JWT_SECRET:my-secret-key}